# Generated by Django 3.2.3 on 2021-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('it', 'IT and Software'), ('data_entry', 'Data Entry'), ('graphic_design', 'Graphic Design'), ('teaching', 'Teaching'), ('home_tuition', 'Home Tuition')], max_length=50),
        ),
    ]
